apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: driver.assigned
  namespace: fleet-manager
  labels:
    strimzi.io/cluster: fleet-kafka
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: vehicle.updated
  namespace: fleet-manager
  labels:
    strimzi.io/cluster: fleet-kafka
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: maintenance.alert
  namespace: fleet-manager
  labels:
    strimzi.io/cluster: fleet-kafka
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: geofence.alert
  namespace: fleet-manager
  labels:
    strimzi.io/cluster: fleet-kafka
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: fleet.vehicle.status
  namespace: fleet-manager
  labels:
    strimzi.io/cluster: fleet-kafka
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: fleet.location.raw
  namespace: fleet-manager
  labels:
    strimzi.io/cluster: fleet-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: fleet.maintenance.alerts
  namespace: fleet-manager
  labels:
    strimzi.io/cluster: fleet-kafka
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: fleet.system.logs
  namespace: fleet-manager
  labels:
    strimzi.io/cluster: fleet-kafka
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
