framework:
    messenger:
        transports:
            kafka_transport:
                dsn: "kafka://fleet-kafka-kafka-bootstrap.fleet-manager.svc.cluster.local:9092"
                serializer: messenger.transport.json_serializer
                options:
                    commit_async: true

        routing:
            'App\Message\*': kafka_transport
