framework:
    messenger:
        transports:
            kafka_fleet:
                dsn: "%env(KAFKA_URL)%"
                serializer: "messenger.transport.native_php_serializer"
                options:
                    commit_async: true

        routing:
            'App\Message\*': kafka_fleet
