services:
  vehicle-service:
    container_name: vehicle-service
    image: vehicle-service
    build: .
    ports:
      - "8001:80"
    environment:
      DATABASE_URL: "postgresql://postgres:sidou_password@database:5432/fleetmanager?serverVersion=16&charset=utf8"
      APP_ENV: prod
      APP_DEBUG: "0"
      APP_SECRET: a_very_secret_key_for_fleet_manager
      DEFAULT_URI: http://localhost:80
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:16-alpine
    container_name: vehicle-service-db
    environment:
      POSTGRES_DB: fleetmanager
      POSTGRES_PASSWORD: sidou_password
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "fleetmanager", "-U", "postgres"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data: 