apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-datasource
  namespace: observabilite
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      url: http://loki-gateway.observabilite.svc.cluster.local
      access: proxy
      isDefault: false
    - name: Prometheus
      type: prometheus
      url: http://prometheus-operated.observabilite.svc.cluster.local:9090
      access: proxy
      isDefault: false
