apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: database
data:
  init.sql: |
    CREATE DATABASE vehicle_db;
    CREATE DATABASE conductor_db;
    CREATE DATABASE maintenance_db;
    CREATE DATABASE localization_db;
    CREATE DATABASE event_db;
    CREATE DATABASE keycloak_db;
