apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintenance-service
  namespace: fleet-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maintenance-service
  template:
    metadata:
      labels:
        app: maintenance-service
    spec:
      containers:
        - name: maintenance-service
          image: fleetmanager-maintenance-service:latest
          imagePullPolicy: Never
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: global-fleet-config
---
apiVersion: v1
kind: Service
metadata:
  name: maintenance-service
  namespace: fleet-manager
spec:
  type: ClusterIP
  selector:
    app: maintenance-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
