apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-service
  namespace: fleet-manager
spec:
  replicas: 1 # Start with 1 to make debugging easier!
  selector:
    matchLabels:
      app: vehicle-service
  template:
    metadata:
      labels:
        app: vehicle-service
    spec:
      containers:
        - name: vehicle-service
          image: fleetmanager-vehicle-service:latest
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: vehicle-service-env
          # livenessProbe:
          #   httpGet:
          #     path: /api
          #     port: 80
          #   initialDelaySeconds: 60
          #   timeoutSeconds: 5
          #   periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: vehicle-service
  namespace: fleet-manager
spec:
  type: LoadBalancer
  selector:
    app: vehicle-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
