apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-service
  namespace: fleet-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vehicle-service
  template:
    metadata:
      labels:
        app: vehicle-service
    spec:
      containers:
        - name: vehicle-service
          image: fleetmanager-vehicle-service:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: APP_ENV
              value: "dev"
            - name: APP_SECRET
              value: "739339f94f63c6ddfc01608764b4b81"
            - name: DATABASE_URL
              value: "postgresql://user:password@db-vehicle:5432/vehicle_db"
            - name: KAFKA_URL
              value: "kafka://fleet-kafka-kafka-bootstrap.fleet-manager.svc.cluster.local:9092"
            - name: CORS_ALLOW_ORIGIN
              value: "^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$"
          livenessProbe:
            httpGet:
              path: /api
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: vehicle-service
  namespace: fleet-manager
spec:
  type: LoadBalancer
  selector:
    app: vehicle-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
