apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-service
  namespace: fleet-manager
spec:
  replicas: 1 # Start with 1 to make debugging easier!
  selector:
    matchLabels:
      app: vehicle-service
  template:
    metadata:
      labels:
        app: vehicle-service
    spec:
      containers:
        - name: vehicle-service
          image: fleetmanager-vehicle-service:latest
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: global-fleet-config
          env:
            - name: CORS_ALLOW_ORIGIN
              value: "^.*$"
            - name: APP_ENV
              value: "dev"

---
apiVersion: v1
kind: Service
metadata:
  name: vehicle-service
  namespace: fleet-manager
spec:
  type: ClusterIP
  selector:
    app: vehicle-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
