api_platform:
    title: "Fleet Management - Vehicle Service"
    version: "1.0.0"
    mapping:
        paths: ["%kernel.project_dir%/src/Entity"]
    graphql:
        enabled: true
        graphiql:
            enabled: true
    docs_formats:
        openapi: ["application/vnd.openapi+yaml", "text/html"]
