# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    serializer:
        enabled: true
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: {}

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
