framework:
    messenger:
        transports:
            kafka_fleet:
                dsn: "enqueue://default"
                serializer: "messenger.transport.native_php_serializer"

        routing:
            'App\Message\VehicleStatusChanged': kafka_fleet
