framework:
    messenger:
        transports:
            kafka_fleet:
                dsn: "kafka://fleet-kafka-kafka-bootstrap.fleet-manager.svc.cluster.local:9092?topic[name]=fleet.vehicle.status"
                serializer: messenger.transport.json_serializer
                options:
                    commit_async: true

        routing:
            'App\Message\VehicleStatusChanged': kafka_fleet
